
#######################################
#######################################
##                                   ##
##  Minimum version: 1.18.2 PaperMC  ##
##  Minimum Towny version: 0.98.4.0  ##
##  Minimum Vault version: v1.7      ##
##                                   ##
#######################################
#######################################

# How to set up TownyPorts:
# https://euromc.net/

uses-economy: true
#If false, players can't set fees on ports, and travellers won't be charged anything.
#Additionally, the /setportprice and /portprice commands will be disabled too.
#Default: true

currency-sign: "$"
#The sign used for economy notifications or errors.
#Default: "$"

minimum-port-fee: 10
#The minimum travel fee a port can have for travellers.
#Default: 10

maximum-port-fee: 100
#The maximum travel fee a port can have for travellers.
#Default: 100

default-port-fee: 50
#The default travel fee for a port's town.
#Default: 50

maximum-port-distance-in-chunks: 200
#The max distance a port can be from another to be travelled to.
#WARNING: TownyPorts requires you to have 16x16 sized town blocks.
#Default: 200

enable-port-arrival-alert: false
#If true, online residents of a town will be alerted whenever someone arrives at their port.
#Default: false

port-travel-warmup-in-ticks: 200
#A second is 20 minecraft ticks. Use that to calculate your warmup time.
#Default: 200










